scheb_two_factor:

    google:
        enabled: true
        server_name: SkyCast
        issuer: SkyCast
        digits: 6
        leeway: 25
        template: security/2fa_template.html.twig

    backup_codes:
        enabled: true
        manager: App\Service\BackupCodeService

    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
